"""20200328 initial migrations

Revision ID: 6f58f857b93d
Revises: 
Create Date: 2020-03-28 18:53:40.663428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f58f857b93d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_area_type")),
    )
    op.create_table(
        "card_suit",
        sa.Column("id", sa.String(length=1), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_suit")),
    )
    op.create_table(
        "card_value",
        sa.Column("id", sa.String(length=1), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=True),
        sa.Column("low_value", sa.Integer(), nullable=True),
        sa.Column("high_value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_value")),
    )
    op.create_table(
        "deck",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("background", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deck")),
    )
    op.create_table(
        "area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_type.id"],
            name=op.f("fk_area_area_type_id_area_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_area")),
    )
    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("suit_id", sa.String(length=1), nullable=True),
        sa.Column("value_id", sa.String(length=1), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("dealt", sa.Boolean(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("deck_position", sa.Integer(), nullable=True),
        sa.Column("area_position", sa.Integer(), nullable=True),
        sa.Column("face_up", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"], ["area.id"], name=op.f("fk_card_area_id_area"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["deck.id"], name=op.f("fk_card_deck_id_deck"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["suit_id"], ["card_suit.id"], name=op.f("fk_card_suit_id_card_suit"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["value_id"], ["card_value.id"], name=op.f("fk_card_value_id_card_value"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card")
    op.drop_table("area")
    op.drop_table("deck")
    op.drop_table("card_value")
    op.drop_table("card_suit")
    op.drop_table("area_type")
    # ### end Alembic commands ###
